[Interface]
PrivateKey = AAAFmnjanVRdU6MwFH3vr+gwvtmlQFuFzvhQa7ftaD8=
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
# Need to find server public key and endpoint from the config
PublicKey = 
Endpoint = 85.237.57.227:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
